spring:
  mvc:
    log-request-details: true
    dispatch-options-request: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 111111
    url: jdbc:postgresql://localhost:5432/software10

#    url: jdbc:mysql://10.16.48.219:3306/ten_Diabetes?characterEncoding=utf-8
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      enabled: true # 开启文件上传
#      file-size-threshold: 2KB # 文件写入磁盘的阈值
#      max-file-size: 100MB
#      max-request-size: 215MB # 最大请求值大小


#    driver-class-name: org.postgresql.Driver
#    username: pg
#    password: root
#    url: jdbc:postgresql://10.16.48.219:5432/software10


#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#prop:
#  upload-folder: src/main/resources/alg/fig

pagehelper:
  helperDialect: postgresql  # 设置数据库类型为PostgreSQL
  reasonable: true      # 分页合理化参数，默认值为 false，设置为 true 后，如果 pageNum 小于 1，则自动设置为 1，如果 pageNum 大于总页数，则自动设置为最后一页
  supportMethodsArguments: true  # 支持通过 Mapper 方法参数来传递分页参数，默认值为 false



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8090

shandong:
  key: tsdsyujbwefy_ywejwbejwb_euwyeyuugdw_u4lppiiisih_diwhywjhewew_sdsdserkhckfsydyg_IAPAIDHLIAUSDS_tftSFASASA_6A6DA9898

file:
  path: src/main/resources/Files

gorit:
  file:
    root:

#      path1: /home/data/WorkSpace/software10/Load/file
#      path2: /home/data/WorkSpace/software10/Load/alg
      path1: G:/wang/projects/software10/software10_backend/src/main/resources/file
#      path2: G:/wang/projects/software10/software10_backend/src/main/resources/alg
      path2: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg
    py:
#      diabetes: /home/data/WorkSpace/software10/Arithmetic/pythonProject/diabetes.py
#      xgbc_rl: /home/data/WorkSpace/software10/Arithmetic/pythonProject/xgbc_rl.py
#      rlv3_2: /home/data/WorkSpace/software10/Arithmetic/pythonProject/rlv3_2.py
#      dqn1: /home/data/WorkSpace/software10/Arithmetic/pythonProject/dqn1.py
#      use_model: /home/data/WorkSpace/software10/Arithmetic/pythonProject/use_model.py

      diabetes: D:/Code/Java/software10/software-software_backend/src/main/resources/alg/xgb.py
      xgbc_rl: C:/Users/pc/PycharmProjects/pythonProject/xgbc_rl.py
      rlv3_2: C:/Users/pc/PycharmProjects/pythonProject/rlv3_2.py
      QLearning: src/main/resources/alg/algorithms/Q_learning.py
      RunQLearning: src/main/resources/alg/algorithms/RunQLearning.py
      dqn1: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/dqn1.py
      use_model: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/use_model.py



      getLackInfos: /root/keti3/backend/software10/alg/algorithms/getLackInfos.py
      RF: /root/keti3/backend/software10/alg/algorithms/RF.py
      XGB: /root/keti3/backend/software10/alg/algorithms/xgb.py
      SVM: /root/keti3/backend/software10/alg/algorithms/SVM.py
      DQN: /root/keti3/backend/software10/alg/algorithms/dqn.py
      KNN: /root/keti3/backend/software10/alg/algorithms/KNN.py
      RUNDQN: /root/keti3/backend/software10/alg/algorithms/RunDQN.py
      RUNSVM: /root/keti3/backend/software10/alg/algorithms/RunSVM.py
      RUNKNN: /root/keti3/backend/software10/alg/algorithms/RunKNN.py
      explainerPath: /root/keti3/backend/software10/alg/models/explainer/
      explanationPath: /root/keti3/backend/software10/alg/models/explanation/
      scalerPath: /root/keti3/backend/software10/alg/models/scaler/
      trainedPath: /root/keti3/backend/software10/alg/models/trained/
      shapPath: /root/keti3/backend/software10/alg/fig/
      GetFillRate: /root/keti3/backend/software10/alg/algorithms/get_fill_rate.py

#      dqn1: C:/Users/pc/PycharmProjects/pythonProject/dqn1.py
#      use_model: C:/Users/pc/PycharmProjects/pythonProject/use_model.py

application:
  python:
#    environment: /home/data/anaconda3/envs/software10/bin/python
    environment: /root/anaconda3/envs/software10/bin/python

resources:
  static-locations: >
    file: src/main/resources/Files





















#spring:
#  datasource:
#    #    url: jdbc:mysql://10.16.48.219:3306/ten_Diabetes?characterEncoding=utf-8
#    #    username: root
#    #    password: 111111
#    #    driver-class-name: com.mysql.cj.jdbc.Driver
#    #  servlet:
#    #    multipart:
#    #      enabled: true # 开启文件上传
#    #      file-size-threshold: 2KB # 文件写入磁盘的阈值
#    #      max-file-size: 100MB
#    #      max-request-size: 215MB # 最大请求值大小
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: 111111
#    url: jdbc:postgresql://schh.work:2208/software4v2
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
##  servlet:
##    multipart:
##      max-file-size: 50MB
##      max-request-size: 50MB
##prop:
##  upload-folder: src/main/resources/alg/fig
#
#pagehelper:
#  helperDialect: postgresql  # 设置数据库类型为PostgreSQL
#  reasonable: true      # 分页合理化参数，默认值为 false，设置为 true 后，如果 pageNum 小于 1，则自动设置为 1，如果 pageNum 大于总页数，则自动设置为最后一页
#  supportMethodsArguments: true  # 支持通过 Mapper 方法参数来传递分页参数，默认值为 false
#
#
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 8090
#
#file:
#  path: /home/data/WorkSpace/Backend/software10/Files/
#
#gorit:
#  file:
#    root:
#
#      #      path1: /home/data/WorkSpace/software10/Load/file
#      #      path2: /home/data/WorkSpace/software10/Load/alg
#      path1: G:/wang/projects/software10/software10_backend/src/main/resources/file
#      #      path2: G:/wang/projects/software10/software10_backend/src/main/resources/alg
#      path2: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg
#    py:
#      #      diabetes: /home/data/WorkSpace/software10/Arithmetic/pythonProject/diabetes.py
#      #      xgbc_rl: /home/data/WorkSpace/software10/Arithmetic/pythonProject/xgbc_rl.py
#      #      rlv3_2: /home/data/WorkSpace/software10/Arithmetic/pythonProject/rlv3_2.py
#      #      dqn1: /home/data/WorkSpace/software10/Arithmetic/pythonProject/dqn1.py
#      #      use_model: /home/data/WorkSpace/software10/Arithmetic/pythonProject/use_model.py
#
#      diabetes: D:/Code/Java/software10/software-software_backend/src/main/resources/alg/xgb.py
#      xgbc_rl: C:/Users/pc/PycharmProjects/pythonProject/xgbc_rl.py
#      rlv3_2: C:/Users/pc/PycharmProjects/pythonProject/rlv3_2.py
#
#      getLackInfos: /home/data/WorkSpace/Backend/software10/alg/algorithms/getLackInfos.py
#      RF: /home/data/WorkSpace/Backend/software10/alg/algorithms/RF.py
#      XGB: /home/data/WorkSpace/Backend/software10/alg/algorithms/xgb.py
#      SVM: /home/data/WorkSpace/Backend/software10/alg/algorithms/SVM.py
#      DQN: /home/data/WorkSpace/Backend/software10/alg/algorithms/dqn.py
#      KNN: /home/data/WorkSpace/Backend/software10/alg/algorithms/KNN.py
#      QLearning: /home/data/WorkSpace/Backend/software10/alg/algorithms/Q_learning.py
#      RUNDQN: /home/data/WorkSpace/Backend/software10/alg/algorithms/RunDQN.py
#      RUNSVM: /home/data/WorkSpace/Backend/software10/alg/algorithms/RunSVM.py
#      RUNKNN: /home/data/WorkSpace/Backend/software10/alg/algorithms/RunKNN.py
#      RunQLearning: /home/data/WorkSpace/Backend/software10/alg/algorithms/RunQLearning.py
#      GetFillRate: src/main/resources/alg/algorithms/get_fill_rate.py
#
#      explainerPath: /home/data/WorkSpace/Backend/software10/alg/models/explainer/
#      explanationPath: /home/data/WorkSpace/Backend/software10/alg/models/explanation/
#      scalerPath: /home/data/WorkSpace/Backend/software10/alg/models/scaler/
#      trainedPath: /home/data/WorkSpace/Backend/software10/alg/models/trained/
#      shapPath: /home/data/WorkSpace/Backend/software10/alg/fig/
#
#
#
#      #      dqn1: C:/Users/pc/PycharmProjects/pythonProject/dqn1.py
#      #      use_model: C:/Users/pc/PycharmProjects/pythonProject/use_model.py
#      dqn1: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/dqn1.py
#      use_model: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/use_model.py
#
#application:
#  python:
#    #    environment: /home/data/anaconda3/envs/software10/bin/python
#    environment: /home/cqupt/anaconda3/envs/software10/bin/python
#
#resources:
#  static-locations: >
#    file: /home/data/WorkSpace/Backend/software10/Files/
