spring:
  datasource:
    url: jdbc:mysql://10.16.48.219:3306/ten_Diabetes?characterEncoding=utf-8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true # 开启文件上传
      file-size-threshold: 2KB # 文件写入磁盘的阈值
      max-file-size: 100MB
      max-request-size: 215MB # 最大请求值大小

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

gorit:
  file:
    root:
      
#      path1: /home/data/WorkSpace/software10/Load/file
#      path2: /home/data/WorkSpace/software10/Load/alg
      path1: G:/wang/projects/software10/software10_backend/src/main/resources/file
#      path2: G:/wang/projects/software10/software10_backend/src/main/resources/alg
      path2: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg
    py:
#      diabetes: /home/data/WorkSpace/software10/Arithmetic/pythonProject/diabetes.py
#      xgbc_rl: /home/data/WorkSpace/software10/Arithmetic/pythonProject/xgbc_rl.py
#      rlv3_2: /home/data/WorkSpace/software10/Arithmetic/pythonProject/rlv3_2.py
#      dqn1: /home/data/WorkSpace/software10/Arithmetic/pythonProject/dqn1.py
#      use_model: /home/data/WorkSpace/software10/Arithmetic/pythonProject/use_model.py

      diabetes: D:/Code/Java/software10/software-software_backend/src/main/resources/alg/xgb.py
      xgbc_rl: C:/Users/pc/PycharmProjects/pythonProject/xgbc_rl.py
      rlv3_2: C:/Users/pc/PycharmProjects/pythonProject/rlv3_2.py

#      dqn1: C:/Users/pc/PycharmProjects/pythonProject/dqn1.py
#      use_model: C:/Users/pc/PycharmProjects/pythonProject/use_model.py
      dqn1: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/dqn1.py
      use_model: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/use_model.py

application:
  python:
#    environment: /home/data/anaconda3/envs/software10/bin/python
    environment: F:/Anaconda3/envs/pytorch/python.exe
