spring:
  datasource:
#    url: jdbc:mysql://10.16.48.219:3306/ten_Diabetes?characterEncoding=utf-8
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      enabled: true # 开启文件上传
#      file-size-threshold: 2KB # 文件写入磁盘的阈值
#      max-file-size: 100MB
#      max-request-size: 215MB # 最大请求值大小
    driver-class-name: org.postgresql.Driver
    username: pg
    password: root
    url: jdbc:postgresql://10.16.48.219:5432/software10
#  servlet:
#    multipart:
#      max-file-size: 50MB
#      max-request-size: 50MB
#prop:
#  upload-folder: src/main/resources/alg/fig

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8088



gorit:
  file:
    root:
      
#      path1: /home/data/WorkSpace/software10/Load/file
#      path2: /home/data/WorkSpace/software10/Load/alg
      path1: G:/wang/projects/software10/software10_backend/src/main/resources/file
#      path2: G:/wang/projects/software10/software10_backend/src/main/resources/alg
      path2: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg
    py:
#      diabetes: /home/data/WorkSpace/software10/Arithmetic/pythonProject/diabetes.py
#      xgbc_rl: /home/data/WorkSpace/software10/Arithmetic/pythonProject/xgbc_rl.py
#      rlv3_2: /home/data/WorkSpace/software10/Arithmetic/pythonProject/rlv3_2.py
#      dqn1: /home/data/WorkSpace/software10/Arithmetic/pythonProject/dqn1.py
#      use_model: /home/data/WorkSpace/software10/Arithmetic/pythonProject/use_model.py

      diabetes: D:/Code/Java/software10/software-software_backend/src/main/resources/alg/xgb.py
      xgbc_rl: C:/Users/pc/PycharmProjects/pythonProject/xgbc_rl.py
      rlv3_2: C:/Users/pc/PycharmProjects/pythonProject/rlv3_2.py
      getLackInfos: src/main/resources/alg/getLackInfos.py
      RF: src/main/resources/alg/RF.py
      XGB: src/main/resources/alg/xgb.py
      SVM: src/main/resources/alg/svm_classify.py
      DQN: src/main/resources/alg/dqn.py
      KNN: src/main/resources/alg/KNN.py
      RUNDQN: src/main/resources/alg/RunDQN.py
      RUNSVM: src/main/resources/alg/RunSVM.py
      RUNKNN: src/main/resources/alg/RunKNN.py


#      dqn1: C:/Users/pc/PycharmProjects/pythonProject/dqn1.py
#      use_model: C:/Users/pc/PycharmProjects/pythonProject/use_model.py
      dqn1: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/dqn1.py
      use_model: C:/Users/33125/IdeaProjects/software-software_backend/src/main/resources/alg/use_model.py

application:
  python:
#    environment: /home/data/anaconda3/envs/software10/bin/python
    environment: F:/Anaconda3/envs/pytorch/python.exe
